include: https://gitlab-templates.ddbuild.io/compute-delivery/v3/compute-delivery.yml

build-docker-image:
  variables:
    IMAGE_NAME: nvidia/vgpu-device-manager
  extends: .build-docker-image

build-merged-nydus-image:
  needs: ["build-docker-image"]
  variables:
    IMAGE_NAME: nvidia/vgpu-device-manager
    MERGE_PLATFORM: "true"
  extends: .build-nydus-image
